
[c]
format = '(via [$symbol($version(-$name) )]($style))'
[lua]
disabled = true

[golang]



[nodejs]
disabled = true

[java]
disabled = true

[package]
format = '(is [$symbol$version]($style) )'

[python]
disabled = true

[ruby]
disabled = true
[rust]
disabled = true
[git_status]
# 本地分支落后于远程分支时的显示符号
behind = "↓"
# 本地分支超前于远程分支时的显示符号
ahead = "↑"
# 工作区有改动时的颜色
#conflicted = "yellow"
# 工作区有已暂存的文件时的颜色
staged = "green"

[character]
success_symbol = "[\uf054](white)" # 
vicmd_symbol = "[\ue62b](white)" # 
error_symbol = "[\uf467](red)" # 



